In [1]:
import os

In [2]:
os.environ['CUDA_VISIBLE_DEVICES']

'0'

It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed

In [3]:
import torch

In [4]:
# Create uninitialized torch tensor
x = torch.empty(5, 3)

In [5]:
x

tensor([[5.6719e-11, 7.3471e+28, 2.6383e+23],
        [2.7376e+20, 1.8040e+28, 1.8750e-19],
        [7.3909e+22, 2.4176e-12, 2.6209e+20],
        [4.1641e+12, 8.9625e-01, 7.9309e+34],
        [7.9439e+08, 3.2604e-12, 7.3113e+34]])

In [6]:
print(x)

tensor([[5.6719e-11, 7.3471e+28, 2.6383e+23],
        [2.7376e+20, 1.8040e+28, 1.8750e-19],
        [7.3909e+22, 2.4176e-12, 2.6209e+20],
        [4.1641e+12, 8.9625e-01, 7.9309e+34],
        [7.9439e+08, 3.2604e-12, 7.3113e+34]])


In [7]:
# create torch tensor with randomized initialization
x = torch.rand(5,3)

In [8]:
x

tensor([[0.7488, 0.1106, 0.4718],
        [0.5385, 0.5577, 0.1871],
        [0.9373, 0.2770, 0.2016],
        [0.3608, 0.8939, 0.4953],
        [0.5614, 0.2027, 0.8604]])

In [9]:
# We can specify the datatype like numpy but via torch type like below
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


In [10]:
# Create torch tensor directly from value
x = torch.tensor([[5.5, 3], [1, 2]])

In [12]:
x

tensor([[5.5000, 3.0000],
        [1.0000, 2.0000]])

In [13]:
# Create tensor using existing tensor's properties
y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[ 0.3177, -1.2846],
        [-0.0872,  0.5012]])


In [14]:
# size() method accesses the shape attribute of tensor
print("y.shape:", y.shape)
print("y.size():", y.size())

y.shape: torch.Size([2, 2])
y.size(): torch.Size([2, 2])


### Operation on torch tensors

In [21]:
x = torch.ones(2,2)

In [22]:
y = torch.rand_like(x)

In [23]:
x

tensor([[1., 1.],
        [1., 1.]])

In [24]:
y

tensor([[0.8840, 0.4993],
        [0.9695, 0.1894]])

In [25]:
print(x+y)

tensor([[1.8840, 1.4993],
        [1.9695, 1.1894]])


In [26]:
# it is the same as
torch.add(x,y)

tensor([[1.8840, 1.4993],
        [1.9695, 1.1894]])

In [27]:
# elementwise conditional check
torch.add(x,y) == (x+y)

tensor([[True, True],
        [True, True]])

In [28]:
# assign operation output to a tensor
result=torch.empty_like(x)

In [29]:
torch.add(x,y, out=result)

tensor([[1.8840, 1.4993],
        [1.9695, 1.1894]])

In [30]:
print(result)

tensor([[1.8840, 1.4993],
        [1.9695, 1.1894]])


In [31]:
# in_place operation is usually suffixed by "_"
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [32]:
x.add_(y)

tensor([[1.8840, 1.4993],
        [1.9695, 1.1894]])

In [33]:
print(x)

tensor([[1.8840, 1.4993],
        [1.9695, 1.1894]])


In [34]:
# Slide and dice like numpy
# get column 1
print(x[:,1])

tensor([1.4993, 1.1894])


In [35]:
# view() method is synonymous to numpy.reshape()
x = torch.randn(4,4)

In [36]:
y = x.view(16)

In [37]:
z = x.view(-1,2)

In [38]:
y

tensor([-0.0057, -0.4139,  0.6684, -0.0835,  0.4412,  0.2422, -0.6327,  0.8162,
        -0.3137, -0.7847,  0.0094,  0.1874,  1.3213,  1.0478,  0.3988,  0.2350])

In [39]:
z

tensor([[-0.0057, -0.4139],
        [ 0.6684, -0.0835],
        [ 0.4412,  0.2422],
        [-0.6327,  0.8162],
        [-0.3137, -0.7847],
        [ 0.0094,  0.1874],
        [ 1.3213,  1.0478],
        [ 0.3988,  0.2350]])

In [40]:
# Special handling - you need to use .item() for tensor with single element
# that is to convert it to scalar!
x = torch.randn(1)

In [41]:
x[0]

tensor(-1.5018)

In [45]:
x.item()

-1.5017832517623901

In [46]:
y[0,1].item()

IndexError: too many indices for tensor of dimension 1

### Numpy Interoperability

In [47]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [48]:
b = a.numpy()

In [49]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [50]:
a

tensor([1., 1., 1., 1., 1.])

In [51]:
import numpy as np

In [52]:
np_array = np.random.rand(4,4)

In [85]:
torch.from_numpy(np_array)

tensor([[0.1876, 0.5505, 0.2291, 0.5843],
        [0.0273, 0.0227, 0.8804, 0.7779],
        [0.2419, 0.2750, 0.5960, 0.6774],
        [0.1495, 0.8690, 0.9035, 0.9829]], dtype=torch.float64)

In [86]:
np_array

array([[0.18763481, 0.55053849, 0.22913961, 0.58432475],
       [0.02734317, 0.02267784, 0.88036385, 0.77794594],
       [0.24191882, 0.27498593, 0.59602202, 0.67741144],
       [0.14952379, 0.86901203, 0.90354017, 0.98286384]])

### Torch tensor on CUDA!

In [87]:
torch_tensor = torch.from_numpy(np_array)

In [88]:
torch_tensor

tensor([[0.1876, 0.5505, 0.2291, 0.5843],
        [0.0273, 0.0227, 0.8804, 0.7779],
        [0.2419, 0.2750, 0.5960, 0.6774],
        [0.1495, 0.8690, 0.9035, 0.9829]], dtype=torch.float64)

In [91]:
# Convert CPU tensor to CUDA tensor
device = torch.device("cuda")
cuda_torch_tensor = torch_tensor.to(device)

In [90]:
torch_tensor

tensor([[0.1876, 0.5505, 0.2291, 0.5843],
        [0.0273, 0.0227, 0.8804, 0.7779],
        [0.2419, 0.2750, 0.5960, 0.6774],
        [0.1495, 0.8690, 0.9035, 0.9829]], dtype=torch.float64)

In [92]:
# We will see the device property with cuda 
cuda_torch_tensor

tensor([[0.1876, 0.5505, 0.2291, 0.5843],
        [0.0273, 0.0227, 0.8804, 0.7779],
        [0.2419, 0.2750, 0.5960, 0.6774],
        [0.1495, 0.8690, 0.9035, 0.9829]], device='cuda:0',
       dtype=torch.float64)

In [93]:
# Create cuda torch tensor directly
torch.randn(3,3, device=torch.device("cuda"))

tensor([[-1.3701,  1.0195,  0.8993],
        [-0.3088, -0.3321, -0.4559],
        [-0.3843,  0.3738,  0.9320]], device='cuda:0')